version: "3.9"

services:

  redis:
    image: redis:7-alpine
    container_name: sec-redis
    ports:
      - "6379:6379"

  fetch_worker:
    build: .
    # command: celery -A app.core.celery_app worker -Q fetch_queue --loglevel=info -c 1
    command: python workers/fetch_worker.py
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    gpus: all

  embed_worker:
    build: .
    command: python workers/embed_worker.py
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    gpus: all

  topic_worker:
    build: .
    command: python workers/topic_worker.py
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - NUMBA_DISABLE_JIT=1              # Force disable JIT
      - PYTHONASYNCIODEBUG=0
      - OMP_NUM_THREADS=1                # Prevent low-level library parallelization
      - MKL_NUM_THREADS=1
      - NUMBA_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
    depends_on:
      - redis
    gpus: all
    
  analysis_worker:
    build: .
    command: python workers/analysis_worker.py
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - NUMBA_DISABLE_JIT=1              # Force disable JIT
      - PYTHONASYNCIODEBUG=0
      - OMP_NUM_THREADS=1                # Prevent low-level library parallelization
      - MKL_NUM_THREADS=1
      - NUMBA_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
    depends_on:
      - redis
    gpus: all

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - fetch_worker
      - embed_worker
      - topic_worker
      - analysis_worker
    gpus:
      all
